### ISSUE TITLE
Crash on launch, not sure what's wrong D:

### ISSUE THREAD

**Issue by Burnhound** [the-realest-stu/Dynamic-Trees-BOP#5] opened 2018-03-06 06:24 UTC
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Dynamic Trees BOP (dynamictreesbop)

I tried adding it to my current pack and crashed. I then took the mod to its own pack with just Biomes o' plenty, Dynamic Trees and Dynamic Trees BOP.. crashed at the same time. I'll attach both crash reports, if anything else is needed let me know :D thank you! (Pardon the pack name if it appears LMAO, its an inside joke for my group)

[crash-2018-03-06_01.17.10-client.txt](https://github.com/the-realest-stu/Dynamic-Trees-BOP/files/1783755/crash-2018-03-06_01.17.10-client.txt)

[crash-2018-03-06_01.20.20-client.txt](https://github.com/the-realest-stu/Dynamic-Trees-BOP/files/1783756/crash-2018-03-06_01.20.20-client.txt)

**Comment by whitestarx0312** [comment] 2018-03-06 07:07
Try updating to the alpha version of dynamic trees https://github.com/the-realest-stu/Dynamic-Trees-BOP/issues/4

**Comment by ferreusveritas** [comment] 2018-03-06 15:18
Duplicate of #4

**Closed by ferreusveritas** 2018-03-06 15:18 UTC
