### ISSUE TITLE
Palm tree leaves have green boxes

### ISSUE THREAD

**Issue by Versimno** [the-realest-stu/Dynamic-Trees-BOP#13] opened 2018-05-18 01:04 UTC
I'm having an issue where palm tree leaves have a box of solid color around them (the same color as foliage).
https://imgur.com/gallery/fKC3J29

Not sure if it's a compatibility issue or not, I have a lot of mods installed.

**Comment by ferreusveritas** [comment] 2018-05-18 01:37
Do you have fast graphics mode enabled or fancy?

**Comment by Versimno** [comment] 2018-05-18 01:38
Fast graphics are enabled

**Comment by ferreusveritas** [comment] 2018-05-18 02:08
Thanks, I'm pretty sure I know what the problem is.  It's late. I'll fix it tomorrow.

**Comment by ferreusveritas** [comment] 2018-05-24 19:27
Fixed in latest beta

**Closed by ferreusveritas** 2018-05-24 19:27 UTC
